/* 内蔵フォールバック銘柄マスタ（symbols.mjs）— 通常は symbols.csv が優先される */
export const CATS = [
  { name:'日本株', items:[
    { s:'4755.T', n:'楽天グループ',               boxes:[10] },
    { s:'5108.T', n:'ブリヂストン',               boxes:[50] },
    { s:'1605.T', n:'INPEX',                    boxes:[20] },
    { s:'3048.T', n:'ビックカメラ',               boxes:[10] },
    { s:'9434.T', n:'ソフトバンク',               boxes:[20] },
    { s:'9020.T', n:'東日本旅客鉄道',             boxes:[50] },
    { s:'8306.T', n:'三菱UFJフィナンシャルグループ', boxes:[20] },
    { s:'7185.T', n:'ヒロセ通商',                 boxes:[20] },
    { s:'5020.T', n:'ENEOSホールディングス',       boxes:[10] },
    { s:'7974.T', n:'任天堂',                    boxes:[100] },
    { s:'4912.T', n:'ライオン',                  boxes:[10] },
    { s:'7611.T', n:'ハイデイ日高',               boxes:[20] },
    { s:'9432.T', n:'NTT',                      boxes:[10] },
    { s:'2117.T', n:'ウェルネオシュガー',          boxes:[5] },
    { s:'7272.T', n:'ヤマハ発動機',               boxes:[20] },
    { s:'2002.T', n:'日清製粉グループ本社',        boxes:[20] },
    { s:'7637.T', n:'白銅',                      boxes:[10] },
    { s:'4045.T', n:'東亞合成',                  boxes:[20] },
    { s:'3003.T', n:'ヒューリック',               boxes:[20] },
    { s:'9418.T', n:'U-NEXTホールディングス',      boxes:[20] },
    { s:'9433.T', n:'KDDI',                     boxes:[5] },
    { s:'5301.T', n:'東海カーボン',               boxes:[20] },
    { s:'2593.T', n:'伊藤園',                    boxes:[20] },
    { s:'5451.T', n:'ヨドコウ',                  boxes:[20] },
  ]},
  { name:'FX', items:[
    { s:'USDJPY=X', n:'ドル円',   boxes:[0.1] },
    { s:'EURJPY=X', n:'ユーロ円', boxes:[0.1] },
    { s:'GBPJPY=X', n:'ポンド円', boxes:[0.2] },
    { s:'AUDJPY=X', n:'豪ドル円', boxes:[0.1] },
    { s:'CADJPY=X', n:'カナダ円', boxes:[0.1] },
    { s:'CHFJPY=X', n:'スイス円', boxes:[0.1] },
    { s:'EURUSD=X', n:'ユーロドル', boxes:[0.001] },
    { s:'GBPUSD=X', n:'ポンドドル', boxes:[0.002] },
    { s:'AUDUSD=X', n:'豪ドルドル', boxes:[0.001] },
  ]},
];
export const ALL = CATS.flatMap(c => c.items.map(it => ({ ...it, cat: c.name })));
